### ISSUE TITLE
Add HACS support

### ISSUE THREAD

**Issue by Vitani** [MichelGerding/Homeassistant-polygonal-zones#1]
It would be lovely if I could add & update this integration using [HACS](https://hacs.xyz/docs/contribute/), and not have to manually copy files

**Comment by MichelGerding** [comment]
Thanks for the suggestion. Didn't think of adding it to the readme. Due to how hacs works you could always have manually  added it to the custom repositories and installed it that. 
Anyways i have added the button to install using hacs

**Comment by Vitani** [comment]
I get the following error when trying to install via HACS
![image](https://github.com/user-attachments/assets/9919b903-f1a5-453c-ab2f-0a93b04670b5)

**Comment by MichelGerding** [comment]
It should work now. when trying to add a dev brach to test some things it installed just fine for me
