### ISSUE TITLE
bekomme neue entitäten bei jedem neustart

### ISSUE THREAD

**Issue by Luft86** [MichelGerding/Homeassistant-polygonal-zones#4]
Habe das Problem das die Entitäten bei jedem Neustart neu angelegt werden mit hochzählender Zahl am Ende, ist das ein Bug oder so gewollt

erster start:    device_tracker.polygonal_zones_handyapp
zweiter start:  device_tracker.polygonal_zones_handyapp2
.
.
.

**Comment by DirkMu** [comment]
@Luft86 how did you solve the issue?

**Comment by Luft86** [comment]
> @Luft86 how did you solve the issue? 

Hi, i reinstalled the addon and the package by itself then IT was gone by itself.

**Comment by DirkMu** [comment]
Thank you. Reinstalling the HACS integration seems to help.
