### ISSUE TITLE
 Requirements for polygonal_zones not found since update HA 2024.12.0

### ISSUE THREAD

**Issue by Sobelix** [MichelGerding/Homeassistant-polygonal-zones#5]
Since the update to HA 2024.12.0 the zones can't be loaded anymore.
Logfiles complaining about the requirement shapely

No need to rush things, just installed it a good week ego to expirement with the zones and dedection of in which zone around the house my cellphone was. 

Here are the log issues:
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 6:52:02 AM (1 occurrences)
Last logged: 6:52:02 AM

Setup failed for custom integration 'polygonal_zones': Requirements for polygonal_zones not found: ['shapely==2.0.5'].

Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 6:52:00 AM (3 occurrences)
Last logged: 6:52:02 AM

Unable to install package shapely==2.0.5: × No solution found when resolving dependencies: ╰─▶ Because shapely==2.0.5 has no wheels with a matching Python ABI tag and you require shapely==2.0.5, we can conclude that your requirements are unsatisfiable.

**Comment by Luft86** [comment]
same problem here, is there any update planned?

**Comment by MichelGerding** [comment]
It should be fixed. 

for some weird reason the latest hass version isn't able to download older pypi packages. and shapely has released a newer version
